DROP TABLE IF EXISTS marking_round;
DROP TABLE IF EXISTS judge_project;
DROP TABLE IF EXISTS criteria;
DROP TABLE IF EXISTS student;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS judge;
DROP TABLE IF EXISTS semester;
DROP TABLE IF EXISTS school;
DROP TABLE databasechangelog;
