DROP TABLE IF EXISTS marking_round;
DROP TABLE IF EXISTS judge_project;
DROP TABLE IF EXISTS student_project;
DROP TABLE IF EXISTS student;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS criteria;
DROP TABLE IF EXISTS semester;
DROP TABLE IF EXISTS judge;
DROP TYPE IF EXISTS role_type;
DROP TABLE databasechangelog;

TRUNCATE TABLE marking_round RESTART IDENTITY CASCADE;
TRUNCATE TABLE judge_project RESTART IDENTITY CASCADE;
TRUNCATE TABLE student_project RESTART IDENTITY CASCADE;
TRUNCATE TABLE student RESTART IDENTITY CASCADE;
TRUNCATE TABLE project RESTART IDENTITY CASCADE;
TRUNCATE TABLE criteria RESTART IDENTITY CASCADE;
TRUNCATE TABLE semester RESTART IDENTITY CASCADE;
TRUNCATE TABLE judge RESTART IDENTITY CASCADE;