spring:
  application:
    name: judging
  datasource:
#    url: jdbc:postgresql://localhost:5432/judgingV3
#    username: postgres
#    password: Elvans@0309
    url: jdbc:postgresql://db:5432/identity_service
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
#    initalization-mode: never
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  liquibase:
    change-log: classpath:sql/db.changelog-master.xml
    enabled: true
  security:
    jwt:
      secret: xxdWXHtgXeXs0vaLSRjrORGDZvuRSoRHEOc43IyiLl6YOOjTW5U11Ae0fRA0vyeAHqOvepKwiHTkB/dLZP+ESw== # base64 secret
      expiration: 43200000 # in milliseconds (12 hours)

server:
  port: ${SERVER_PORT:9000}

frontend:
  domain:
    url: ${FRONTEND_DOMAIN_URL:http://localhost:5173}
